Started Exchange view
abatplus/bumpit_mobile pull request #22
Opened 2020-07-15 13:32 UTC by ajenkuhnabat

2020-07-15 13:37 UTC, michaeltheobald approved these changes

2020-07-15 13:37 UTC, haraldschaefer approved these changes

2020-07-15 13:37 UTC, haraldschaefer commented on src/components/SwapViewListItem.tsx
> +type OwnProps = {
bessere Benennung 'OwnProps' ist so nichts sagend

2020-07-15 13:37 UTC, haraldschaefer commented on src/pages/SwapView.tsx
> +                <IonLabel className="swap-footer-button-text">Alle anfragen</IonLabel>
lokalisieren

2020-07-15 13:37 UTC, haraldschaefer commented on src/pages/SwapView.tsx
> +                <IonLabel className="swap-footer-button-text">Alle akzeptieren</IonLabel>
lokalisieren

2020-07-16 09:24 UTC, michaeltheobald approved these changes

2020-07-16 09:24 UTC, michaeltheobald commented on src/components/SwapViewListItem.tsx
> +        stateText = 'Warte auf Bestätigung...';
Muss man hier auch wieder lokalisieren?

2020-07-16 09:24 UTC, michaeltheobald commented on src/components/SwapViewListItem.tsx
> +            return onAccept();
Einmal wird die Funktion geliefert, die anderen beide Male das Ergebnis

2020-07-16 09:24 UTC, michaeltheobald commented on src/pages/SwapView.tsx
> +                <IonLabel className="swap-footer-button-text">Alle anfragen</IonLabel>
Sollten wir dann auch noch direkt eine Zahl der noch nicht angefragten dranschreiben?

2020-07-16 09:24 UTC, michaeltheobald commented on src/pages/SwapView.tsx
> +                <IonLabel className="swap-footer-button-text">Alle akzeptieren</IonLabel>
Eine Zahl der noch zu akzeptierenden?

2020-07-17 08:28 UTC, haraldschaefer approved these changes

2020-07-17 08:29 UTC, haraldschaefer commented on src/components/SwapViewListItem.tsx
> +            return onAccept();
sollte korrekt sein

2020-07-17 08:29 UTC, haraldschaefer commented on src/components/SwapViewListItem.tsx
> +        stateText = 'Warte auf Bestätigung...';
wurde lokalisiert

2020-07-17 08:29 UTC, haraldschaefer commented on src/components/SwapViewListItem.tsx
> +type OwnProps = {
geändert

2020-07-17 08:47 UTC, michaeltheobald requested changes

2020-07-17 08:47 UTC, michaeltheobald commented on src/Server/ICardExchangeEvents.ts
> +export default interface ICardExchangeEvents {
wofür brauchen wir das Interface?

2020-07-17 08:47 UTC, michaeltheobald commented on src/Server/ICardExchangeServer.ts
> +  Events: ICardExchangeEvents;
Bisher wird das nicht nach aussen benötigt

2020-07-17 08:47 UTC, michaeltheobald commented on src/Server/SwapViewCardExchangeClient.ts
> +    // peers.forEach((entry) => list.push(JSON.parse(entry)));
braucht man das noch?

2020-07-17 08:47 UTC, michaeltheobald commented on src/Server/SwapViewCardExchangeClient.ts
> +    // peers.forEach((entry) => list.push(JSON.parse(entry)));
s.o.

2020-07-17 08:47 UTC, michaeltheobald commented on src/Server/SwapViewCardExchangeClient.ts
> +    this.dispatch(Actions.Swap.updateList(peers.map((entry) => JSON.parse(entry))));
Da steht das gleiche wie bei subscribed. Sollte man das zusammenfassen oder kommt noch spezielle Logik hinzu?

2020-07-17 08:47 UTC, michaeltheobald commented on src/Server/SwapViewCardExchangeClient.ts
> +  // send a revoke request
'remove request successfully sent'

2020-07-17 08:47 UTC, michaeltheobald commented on src/components/SwapViewListItem.tsx
> +type SwapViewListItemType = {
macht man hier nicht normalerweise ein Interface draus?

2020-07-17 08:47 UTC, michaeltheobald commented on src/components/SwapViewListItem.tsx
> +const SwapViewListItem: React.FC<SwapViewListItemType> = ({ name, state, onDoRequest, onAbortRequest, onAcceptRequest }) => {
kann man hier den type nutzen, wie er oben definiert ist?

2020-07-17 08:47 UTC, michaeltheobald commented on src/i18n/en/vcard.json
> +    "message": "Wait for contacts..."
'Waiting...

2020-07-17 08:47 UTC, michaeltheobald commented on src/i18n/en/vcard.json
> +    "message": "Wait for acceptance..."
'Waiting...

2020-07-17 08:47 UTC, michaeltheobald commented on src/i18n/en/vcard.json
> +    "message": "Request accepted. Send data..."
...Sending data...

2020-07-17 08:47 UTC, michaeltheobald commented on src/store/actions/swapActions.ts
> +export enum ActionTypes {
Muss das enum hier noch raus?

2020-07-17 08:47 UTC, michaeltheobald commented on src/store/reducers/SwapReducer.ts
> + * Reorder so that the old element won't be shown on the bottom of the list.
Nice

2020-07-17 09:04 UTC, haraldschaefer commented on src/Server/ICardExchangeEvents.ts
> +export default interface ICardExchangeEvents {
war zum mocken notwendig

2020-07-17 09:08 UTC, haraldschaefer commented on src/Server/SwapViewCardExchangeClient.ts
> +    this.dispatch(Actions.Swap.updateList(peers.map((entry) => JSON.parse(entry))));
könnte noch spezielle logik hinzukommen

2020-07-17 09:08 UTC, haraldschaefer commented on src/store/actions/swapActions.ts
> +export enum ActionTypes {
ja

2020-07-17 09:11 UTC, haraldschaefer commented on src/Server/ICardExchangeServer.ts
> +  Events: ICardExchangeEvents;
bisher nicht aber wenn es nach außen nicht benötigt werden sollte kann später die ganze Seite auch raus

2020-07-17 09:23 UTC, michaeltheobald approved these changes

2020-07-17 09:25 UTC, merged